FROM ubuntu:16.04

RUN apt-get update -y
RUN apt-get install wget -y
RUN wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get install apt-transport-https -y
RUN apt-get update -y
RUN apt-get install libcurl4-openssl-dev -y
RUN apt-get install aspnetcore-runtime-2.2 -y
RUN apt-get install gss-ntlmssp -y
RUN apt-get autoremove -y

ENV DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0

WORKDIR /app
COPY ./app/out /app

EXPOSE 4321
ENTRYPOINT ["dotnet", "TeamFollowUpConsole.dll"]